
import '../../../../core/utils/routes/api_services_http.dart';
import '../model/login_model.dart';
class PostDataServices {
  Future<Autogenerated> postData({required email, required password}) async {
    Map<String,dynamic> data = await ApiServiceHttp().post(
        uri: 'https://alandalosschool.com/api/auth/login',
        body: {
          'email':email,
          'password':password,});
    print('the data from data services : $data');
    return  Autogenerated.fromJson(data);


  }
}
