import 'package:bloc/bloc.dart';
import '../../data/data_source.dart';
import '../../model/login_model.dart';
import 'login_state.dart';

class LoginCubit extends Cubit<LoginState> {
  LoginCubit(this.postDataServices) : super(LoginInitial());
  final PostDataServices postDataServices;
  Future<void> getAllData({required email, required password}) async {
    Autogenerated data;
    data = await postDataServices.postData(
        email: email, password: password);
    if(data.status == 200)
      {
        emit(FeaturedRepositorySuccess(data.data!));
      }
    else {
      emit(FeaturedRepositoryFailure(data.message!));

    }
  }
  }

